import { Image } from "./interfaces";

export const imageObjectList: Image[] = [
  {
    type: "Prebuilt PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Creator RDY Y40BG201",
    geForce:'GeForce RTX 3080 - 10GB',
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    price: "$3,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Buy now",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Prebuilt PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Gaming RDY SLMRG211",
    operatingSystem: "Windows 11 Pro",
    geForce:'GeForce RTX 3080 - 10GB',
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    price: "$1,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Buy now",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 13th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    geForce:'GeForce RTX 3080 - 10GB',
    discount: "SAVE $200",
    price: "$3,666",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Estimate Ship By 07/18/2023",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "AMD Ryzen 9 Ultra Gaming Daily Deal",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    geForce:'GeForce RTX 3080 - 10GB',
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    price: "$1,989",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Estimate Ship By 07/18/2023",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 14th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    geForce:'GeForce RTX 3080 - 10GB',
    discount: "SAVE $200",
    price: "$5,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 23th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    geForce:'GeForce RTX 3080 - 10GB',
    discount: "SAVE $200",
    price: "$3,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 19th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    price: "$9,549",
    oldprice: "$3,999",
    geForce:'GeForce RTX 3080 - 10GB',
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 10th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    geForce:'GeForce RTX 3080 - 10GB',
    price: "$3,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
  {
    type: "Custom PC",
    imageSrc: "/gaming-pc-01-Y60-002-Main-2400.webp",
    name: "Intel 22th Gen Performance Daily",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel® Core™ i9-13900KF CPU",
    geForce:'GeForce RTX 3080 - 10GB',
    graphicsCard: "GeForce RTX 4090 - 24GB",
    storage: "2TB M.2 NVMe GEN4 SSD",
    ram: "32GB DDR5-6000MHz RGB RAM",
    discount: "SAVE $200",
    price: "$8,549",
    oldprice: "$3,999",
    starting: "Starting at $87.22/mo with",
    shipping: " Free Shipping",
    delivery: "Delivery By Friday, Jul 7",
    buttonType: "Customize",
    affirm: "/Affirm_logo.svg.png",
  },
];
